variables:
  IMAGE_TAG: $CI_COMMIT_REF_SLUG

stages:
  - test

before_script:
  - eval `ssh-agent -s`
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

test:
  stage: test
  script:
    - ls
    - ls docker/test
    - make docker-test
